name: Release pensjon-opptjening-azure-ad-client

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v5

      - name: 'Set up JDK 17'
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: 'Configure git'
        run: git config user.email "${{ github.actor }}@users.noreply.github.com" && git config user.name "Github Actions"

      - name: 'Capture version number for release'
        run: echo "VERSION=$(grep -v '^#' gradle.properties | grep 'version=' | cut -d '=' -f2 | xargs)" >> $GITHUB_ENV

      - name: 'Build and update version'
        run: ./gradlew build release -Prelease.useAutomaticVersion=true

      - name: 'Checkout release-version'
        uses: actions/checkout@v5
        with:
          ref: "release-${{ env.VERSION }}"

      - name: 'Publish package'
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}